name: GitHub
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go latest
      uses: actions/setup-go@v3

    - run: go version

    - name: Get dependencies
      run: go get ./...

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -cover -coverprofile=coverage.out -covermode=atomic -race ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Benchmark
      run: go test -benchtime 5x -cpu 1,2,4 -bench=. ./... | grep Benchmark
